title: A.S. Graphic Studio
email: asgraphicstudio@ucsd.edu
description: Your innovative design solution! We work with UC San Diego students, staff and faculty to build upon their design concepts and bring them to life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://asgraphicstudio.ucsd.edu" # the base hostname & protocol for your site, e.g. http://example.com
github_username: emilynguyen

# Build settings
markdown: kramdown
plugins:
  #- jekyll-autoprefixer
sass:
  sass_dir: _sass
include: ["_pages"]
kramdown:
  input: GFM
